### ISSUE TITLE
Remove proto code reference from javadoc comments

### ISSUE THREAD

**Issue by eaball35** [googleapis/gapic-generator-java#1002]
Referring to the proto in the javadoc comments doesn't add much value for external users and can be confusing in reference docs. I think we can just remove including this entirely from generation.

`<code>.google.devtools.clouderrorreporting.v1beta1.ErrorContext context = 5;</code>`

https://github.com/googleapis/java-errorreporting/blob/main/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ErrorEventOrBuilder.java#L159

https://cloud.google.com/java/docs/reference/google-cloud-errorreporting/latest/com.google.devtools.clouderrorreporting.v1beta1.ErrorEventOrBuilder

**Comment by blakeli0** [comment]
If this file is in the proto folder, I think it is generated by the `java_proto_library` which is not the responsibility of this repo.

**Comment by blakeli0** [comment]
This code is generated by the Bazel protobuf plugin, not the Java micro generator. Please feel free to open another issue in https://github.com/protocolbuffers/protobuf if you still think this is an issue.
