### ISSUE TITLE
Skip generating REST methods if the RPC does not have HTTP annotation.

### ISSUE THREAD

**Issue by blakeli0** [googleapis/gapic-generator-java#1117]
We should not generate REST methods if the RPC does not have HTTP annotation. See this [proto](https://github.com/googleapis/googleapis/blob/e69c47f438eb55caec51716fbc2b8a42313ca024/google/cloud/mediatranslation/v1beta1/media_translation.proto#L39) and the [proto](https://github.com/googleapis/googleapis/blob/e69c47f438eb55caec51716fbc2b8a42313ca024/google/cloud/language/v1/language_service.proto#L38) that has it.
In this case, we are already [not generating REST methods](https://github.com/googleapis/google-cloud-java/blob/main/java-mediatranslation/google-cloud-mediatranslation/src/main/java/com/google/cloud/mediatranslation/v1beta1/stub/HttpJsonSpeechTranslationServiceStub.java) because it's BIDI streaming, but we need to use the HTTP annotation as the filter instead of using RPC type.

In addition, we should not generating the client at all if there are no RPCs with HTTP annotation. See [go/actools-diregapic-parallelization-sync](http://go/actools-diregapic-parallelization-sync) for details.

There could be multiple reasons an RPC does not have HTTP annotation:

- The RPC is not supposed to be supported by REST. e.g. BIDI streaming methods
- The RPC is not yet supported by the backend service, but could be supported in the future
- The proto is not properly configured.

**Comment by lqiu96** [comment]
Closing this issue as we've merged in both Part 1 and Part 2 of this issue.
