### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator-java#117]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by miraleung** [comment]
Will turn this on when the first iteration of the microgenerator is done, current estimate is the start of October.

**Comment by JustinBeckwith** [comment]
Curiosity - which parts prevent us from enabling it now?  Not pushing back, just trying to learn.

**Comment by miraleung** [comment]
Development speed.

**Comment by JustinBeckwith** [comment]
Sure - I guess what I was asking is:
- Are you doing `git push origin master`?
- Or are you doing PRs, and not requiring code reviews?
- Or do you have tests, you just don't care right now if they're passing?

**Comment by miraleung** [comment]
Our development model merges PRs in from non-master branches,  and OWNERS approval with passing tests, linter checks, and the CLA check. Without any of this, there can be no pushes to master. So we do have master branch protection, and we can enable the stricter variant in this bug soon enough.

**Comment by SurferJeffAtGoogle** [comment]
Mira, your existing process sounds good.  Is there a reason to not enable branch protection today?

**Comment by miraleung** [comment]
Closing as fixed.
