### ISSUE TITLE
Monorepo migration breaks the pre-commit mvn fmt step

### ISSUE THREAD

**Issue by lqiu96** [googleapis/gapic-generator-java#1253]
Pre-commit hooks setup via DEVELOPMENT.md result in this error on commit:

```
[ERROR] No plugin found for prefix 'fmt' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/alicejli/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```

The mvn fmt plugin has to be invoked by:
`mvn com.coveo:fmt-maven-plugin:format` to run.

The temp solution is to remove the pre-commit hooks and manually invoke the command above to format the repo.

---
When a solution is found, please also update the DEVELOPMENT.md file!

**Comment by blakeli0** [comment]
This issue is already fixed in #1266
