### ISSUE TITLE
no such attribute

### ISSUE THREAD

**Issue by Vinccool96** [googleapis/gapic-generator-java#1296]
I am using the [googleapi](https://github.com/googleapis/googleapis) repo on Ubuntu 22.04. This library causes it to bug

#### Steps to reproduce

  1. Clone googleapi
  2. run `bazel build //...`

Error messages:

```
ERROR: /home/vinc/.cache/bazel/_bazel_vinc/b765feac83d3b5d50b722a407f17c1a4/external/gapic_generator_java/rules_java_gapic/BUILD.bazel:7:8: @gapic_generator_java//rules_java_gapic:gradlew: no such attribute 'extension' in '_real_pkg_tar' rule
ERROR: /home/vinc/.cache/bazel/_bazel_vinc/b765feac83d3b5d50b722a407f17c1a4/external/gapic_generator_java/rules_java_gapic/BUILD.bazel:7:8: @gapic_generator_java//rules_java_gapic:gradlew: no such attribute 'files' in '_real_pkg_tar' rule
ERROR: /home/vinc/.cache/bazel/_bazel_vinc/b765feac83d3b5d50b722a407f17c1a4/external/gapic_generator_java/rules_java_gapic/BUILD.bazel:7:8: @gapic_generator_java//rules_java_gapic:gradlew: no such attribute 'mode' in '_real_pkg_tar' rule
ERROR: /home/vinc/.cache/bazel/_bazel_vinc/b765feac83d3b5d50b722a407f17c1a4/external/gapic_generator_java/rules_java_gapic/BUILD.bazel:7:8: @gapic_generator_java//rules_java_gapic:gradlew: no such attribute 'modes' in '_real_pkg_tar' rule
ERROR: /home/vinc/IntelliJProjects/googleapis/grafeas/v1/BUILD.bazel:179:31: Target '@gapic_generator_java//rules_java_gapic:resources/gradle/proto.gradle.tmpl' contains an error and its package is in error and referenced by '//grafeas/v1:proto-google-cloud-grafeas-v1-java-resources'
```

**Comment by lqiu96** [comment]
Thanks @Vinccool96 for raising this issue. 

In https://github.com/googleapis/gapic-generator-java/blob/main/DEVELOPMENT.md, we do recommend installing bazelisk to use the bazel version specified in the .bazeliskrc file (it should match the version specified in googleapis' .bazeliskrc file at https://github.com/googleapis/googleapis/blob/e42829fac916ce9982c7de05bf242d611e7066f1/.bazeliskrc#L2)

We should fix this issue with Bazel 6 compatibility and I see there is a PR with a potential fix going around. I'm going to close this one and we can track this bug in the other issue. Thanks again!
