### ISSUE TITLE
HttpJsonClientInterceptorTest.testCustomInterceptor is flaky

### ISSUE THREAD

**Issue by blakeli0** [googleapis/gapic-generator-java#1322]
See https://github.com/googleapis/gax-java/runs/7581553740?check_suite_focus=true for the failure in gradle build and https://github.com/googleapis/gax-java/runs/7582163011?check_suite_focus=true for failure in maven build.

**Comment by lqiu96** [comment]
This has been resolved in: https://github.com/googleapis/gapic-generator-java/pull/1162
