### ISSUE TITLE
`Page` do not easily support Java Streams

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/gapic-generator-java#1426]
Add stream support for `com.google.api.gax.paging.Page`

**Comment by blakeli0** [comment]
What does "Yoshi APIs" mean? I guess you mean GAPIC libraries? I think we should stop using the term "Yoshi" as the team does not exist anymore.

**Comment by JoeWang1127** [comment]
Thanks for the advice, @blakeli0, I've changed the title.
