### ISSUE TITLE
End-to-end debug the generator

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/gapic-generator-java#1455]
Sometimes developers want to debug the generator starting from protobuf compiler plugin to see the file generation process.

The generator should give guidance on how to do that.

**Comment by blakeli0** [comment]
FYI, there is an existing [doc](https://docs.google.com/document/d/1E6aFtLlNNWOcZzQyt6xzOhEKkIvyAJv4VnjZdsreq0s/edit?resourcekey=0-pI_23DusEimOEOuZ74NvVA#heading=h.nz7y72jvqdtb) that explains how to debug within the generator by using pre-generated zip that contains all the protobuf generated java source code. I never tried it again after monorepo migration but it should still work. 
CC: @suztomo

**Comment by suztomo** [comment]
I feel https://github.com/googleapis/gapic-generator-java/pull/1454 is simpler than the instruction in the document.
