### ISSUE TITLE
[api-common]: from v2.3.1 `com.google.auto.value:auto-value` has `compile` scope

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/gapic-generator-java#1618]
As of `com.google.api:api-common:v2.3.1`[1] `com.google.auto.value:auto-value` has `compile` scope causing it to be included as a transitive dependency.

In `com.google.api:api-common:v2.2.2`[2], auto-value is not present in the compile dependency list.

I suspect this happened when the switch from gradle to maven was going on. We might need to update some config [3].

[1] https://central.sonatype.com/artifact/com.google.api/api-common/2.3.1
[2] https://central.sonatype.com/artifact/com.google.api/api-common/2.2.2
[3] https://github.com/google/auto/blob/main/value/userguide/index.md#with-maven

Originally raised as a java-storage issue in https://github.com/googleapis/java-storage/issues/1973

**Comment by suztomo** [comment]
Checking.

**Comment by suztomo** [comment]
It was added in https://github.com/googleapis/api-common-java/pull/389 . Removing it in #1621.
