### ISSUE TITLE
Add support for ~ separated resource names

### ISSUE THREAD

**Issue by nwbirnie** [googleapis/gapic-generator-java#449]
In ads API, we use resource names which contain ~ to delimit multiple IDs in a path segment. For example:

```
message AdGroupAd {
  option (google.api.resource) = {
    type: "googleads.googleapis.com/AdGroupAd"
    pattern: "customers/{customer_id}/adGroupAds/{ad_group_id}~{ad_id}"
  };
```

The current microgenerator implementation doesn't appear to support this, and instead just generates a single param in its place.

Link to protos: http://shortn/_zIPrXkqkoU

**Comment by miraleung** [comment]
Fixed in $450.
