### ISSUE TITLE
Increase code coverage in generated client libraries

### ISSUE THREAD

**Issue by askmeegs** [googleapis/gapic-generator-java#593]
https://github.com/googleapis/java-cloudbuild/pull/343

see: `codecov/patch — 77.14% of diff hit (target 81.69%)`

**Comment by miraleung** [comment]
Summarizing an offline discussion: This seems to be caused by the removal of `@BetaApi` annotations, which probably were previously skipped by code coverage. There doesn't seem to be an effective delta, but we should increase coverage in a future microgenerator release.

**Comment by blakeli0** [comment]
We are working on new test strategy for generated client libraries, the goal may not be improving the code coverage number.
