### ISSUE TITLE
Remove final keyword from generated client close() method

### ISSUE THREAD

**Issue by jfschmakeit** [googleapis/gapic-generator-java#650]
The generated `close()` method in the client class should not be final, so that clients can override it as needed.

Context:
The [Google Photos Library API client library](https://github.com/google/java-photoslibrary/), extends the generated client library and wraps some additional functionality in its main client class [`PhotosLibraryClient`](https://github.com/google/java-photoslibrary/blob/main/photoslibraryapi/src/main/java/com/google/photos/library/v1/PhotosLibraryClient.java). In particular, it includes upload functionality that is handled via an internal `BackgroundResource` that must be cleaned up after use. 

Unfortunately, the `close()` method included in the autogenerated client class ([`InternalPhotosLibraryClient`](https://github.com/google/java-photoslibrary/blob/main/photoslibraryapi/src/main/java/com/google/photos/library/v1/internal/InternalPhotosLibraryClient.java)) is marked as `final`, which means that we are not able to override it and implement our own `close()` method. 
As proposed in https://github.com/google/java-photoslibrary/pull/40 we are considering manually removing the `final` keyword from the generated method so that it can be overridden in our client class. Ideally this is something that can be done at the Java microgenerator level, so that we don't have to remove the keyword when the client library is regenerated.

**Comment by miraleung** [comment]
Removing the keyword from code generation would affect all 170+ APIs we produce, so given the lack of other requests from client teams, the manual post-processing step would be preferable.

@vam-google FYI - here is a use case that requires post-processing but is not currently using synthtool.
