### ISSUE TITLE
Generator should respect deprecated annotations

### ISSUE THREAD

**Issue by chingor13** [googleapis/gapic-generator-java#703]
For gapic service rpcs:

`option deprecated = true`

Example: [proto](https://github.com/googleapis/googleapis/blob/d76f26f335b2b570b7e19d938f35f9894236e565/google/container/v1/cluster_service.proto#L175) [client](https://github.com/googleapis/java-container/blob/c9c5eed29645a849b4a4ddb604c1fbdc76534785/google-cloud-container/src/main/java/com/google/cloud/container/v1/ClusterManagerClient.java#L1234-L1238)

Expected:
* The method should be annotationed `@Deprecated`
* The javadoc should contain `@deprecated` with a note to replacement (if possible)

**Comment by stephaniewang526** [comment]
This is also not working for [services](https://github.com/googleapis/java-bigquerystorage/pull/982/files#diff-c10c241db71ebd11ae8cbc21a6efb2adcf9e332654ab49182ca7750924d4b997L94) --> service in the proto has been marked as deprecated but the grpc client has not been marked accordingly.

**Comment by miraleung** [comment]
Thanks for filing this bug, I'll start on this. From what I understand, the expected generated code should be the following. 

```
  // AUTO-GENERATED DOCUMENTATION AND METHOD.
  /**
   * Sets the locations for a specific cluster. Deprecated. Use
   * [projects.locations.clusters.update](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters/update)
   * instead.
   *
   * <p>Sample code: <goes here>
   *
   * @param <all params, return go here>
   * @throws com.google.api.gax.rpc.ApiException if the remote call fails
   * @deprecated 
   */
 @Deprecated
  public final Operation setLocations(String name, List<String> locations) {
    SetLocationsRequest request =
        SetLocationsRequest.newBuilder().setName(name).addAllLocations(locations).build();
    return setLocations(request);
  }
  ```

**Comment by stephaniewang526** [comment]
Yes, thank you Mira.
