### ISSUE TITLE
Fix comment builder structure

### ISSUE THREAD

**Issue by miraleung** [googleapis/gapic-generator-java#704]
The comment Builder classes currently break the expected immutability pattern. That is, Builder setFoo() should not alter the class, but return a newly-constructed Builder object with the desired changes applied.

@xiaozhenliu-gg5 FYI

**Comment by hkdevandla** [comment]
Vadym, can you triage this and assign this to someone in cloud java - seems like a good starter task to ramp up. Thanks!

**Comment by suztomo** [comment]
@miraleung If you still need this issue, please reopen this. I'm cleaning up old tickets.

[JavaDocComment.java](https://github.com/googleapis/gapic-generator-java/blob/d13d3c381bb64e1833cbc443a12781084e89494b/gapic-generator-java/src/main/java/com/google/api/generator/engine/ast/JavaDocComment.java and [LineComment.java](https://github.com/googleapis/gapic-generator-java/blob/4c9606323e88983151c71e6493868d739a395960/gapic-generator-java/src/main/java/com/google/api/generator/engine/ast/LineComment.java) use `AutoValue.Builder` for their builder classes. It should follow the Google standard immutability.
