### ISSUE TITLE
Remove extraneous `setBody` on `MethodDefinition` in Test composer

### ISSUE THREAD

**Issue by miraleung** [googleapis/gapic-generator-java#780]
https://github.com/googleapis/gapic-generator-java/blob/master/src/main/java/com/google/api/generator/gapic/composer/grpc/ServiceClientTestClassComposer.java#L209

**Comment by miraleung** [comment]
@vam-google  Please reassign to Gabriel when he gets his GitHub account setup.

**Comment by GabrielGonzalezDiaz** [comment]
What needs to be removed is '.setBody(body)' correct?
