### ISSUE TITLE
license-header check stopped working

### ISSUE THREAD

**Issue by blakeli0** [googleapis/gapic-generator-java#984]
license-header check for recent builds has being failing since around 15 days ago, probably because the servers Github actions run on upgraded go version from 1.17.7 to 1.18, and newer version of go now requires some additional config file. See this [link](https://github.com/googleapis/gapic-generator-java/runs/6099235480?check_suite_focus=true) for details.

Nice to have: It would be great to have this work in local development as well(part of bazel test?), so that we don't have to wait until the check fails on Github to fix the license headers.

**Comment by suztomo** [comment]
Memo:

```
Run go get -u github.com/google/addlicense
  go get -u github.com/google/addlicense
  addlicense -c "Google LLC" -l apache -check $(find $PWD -type f -name '*.java' ! -iname '*PlaceholderFile.java')
  shell: /usr/bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.18.0/x6[4](https://github.com/googleapis/gapic-generator-java/runs/6099235480?check_suite_focus=true#step:4:4)
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```
